name: ncdevtoolchecks

on:
  push:
  pull_request:
  schedule:
    - cron: '30 19 * * 0'  # 19:30 every Sunday
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Enable parallel cmake
      run: python ./devel/bin/ncdevtool nprocs --enable-github-parallel

    - name: pip install deps
      run: pip install -r ./devel/reqs/requirements_devel.txt

    - name: checks
      run: ./devel/bin/ncdevtool check -n "fix""me"
